### ISSUE TITLE
issue causing server to mute random players 

### ISSUE THREAD

**Issue by mayersgamer** [oqyh/cs2-Vote-GoldKingZ#10]
its causing server to go mute mode randomly , some players cant hear other but they can talk , big mess going on

**Comment by oqyh** [comment]
> its causing server to go mute mode randomly , some players cant hear other but they can talk , big mess going on

check your config mute section mini players set it that hard to mute normal players
after that check people who got mute Vote-GoldKingZ/Cookies/
if nothing helps check other plugins may do this issue
