### ISSUE TITLE
Server Lags

### ISSUE THREAD

**Issue by Mr-Robot-ops** [oqyh/cs2-Vote-GoldKingZ#4]
Unfortunately, the plugin is currently still too laggy for me. 

Tested on a modded Kuz Linux server with the Hide and Seek mode and the map Infernohideaseek. Other cards caused slightly less longer server response times. Furthermore, my observation was that with every additional function activated in the config, the server response time increases.

120.599999 UNEXPECTED LONG FRAME DETECTED: 66.47ms elapsed, 65.91ms sim time, 3 ticks, 7706..7708.
120.694851 UNEXPECTED LONG FRAME DETECTED: 94.85ms elapsed, 94.28ms sim time, 5 ticks, 7709..7713.
120.815040 UNEXPECTED LONG FRAME DETECTED: 120.19ms elapsed, 119.53ms sim time, 6 ticks, 7714..7719.
Excessive frame time of 120.19ms clamped.  Acting as if the frame only took 100.00ms
120.923818 UNEXPECTED LONG FRAME DETECTED: 108.78ms elapsed, 108.27ms sim time, 6 ticks, 7720..7725.
Excessive frame time of 108.78ms clamped.  Acting as if the frame only took 100.00ms
121.057598 UNEXPECTED LONG FRAME DETECTED: 133.78ms elapsed, 133.14ms sim time, 7 ticks, 7726..7732.
Excessive frame time of 133.78ms clamped.  Acting as if the frame only took 100.00ms
121.168850 UNEXPECTED LONG FRAME DETECTED: 111.25ms elapsed, 110.68ms sim time, 6 ticks, 7733..7738.
Excessive frame time of 111.25ms clamped.  Acting as if the frame only took 100.00ms
121.240432 UNEXPECTED LONG FRAME DETECTED: 71.58ms elapsed, 71.22ms sim time, 6 ticks, 7739..7744.
121.302142 UNEXPECTED LONG FRAME DETECTED: 61.71ms elapsed, 61.39ms sim time, 5 ticks, 7745..7749.
121.350852 UNEXPECTED LONG FRAME DETECTED: 48.71ms elapsed, 48.41ms sim time, 4 ticks, 7750..7753.
121.386033 UNEXPECTED LONG FRAME DETECTED: 35.18ms elapsed, 34.91ms sim time, 3 ticks, 7754..7756.
121.412232 UNEXPECTED LONG FRAME DETECTED: 26.20ms elapsed, 25.88ms sim time, 2 ticks, 7757..7758.
121.436107 UNEXPECTED LONG FRAME DETECTED: 23.88ms elapsed, 23.65ms sim time, 2 ticks, 7759..7760.

![grafik](https://github.com/oqyh/cs2-Vote-GoldKingZ/assets/55334802/40f2d15d-2b93-405a-954a-b57d488502c6)
![grafik](https://github.com/oqyh/cs2-Vote-GoldKingZ/assets/55334802/f5057d41-2c41-4c5b-8e14-03c0d1440479)

**Comment by oqyh** [comment]
> Unfortunately, the plugin is currently still too laggy for me.
> 
> Tested on a modded Kuz Linux server with the Hide and Seek mode and the map Infernohideaseek. Other cards caused slightly less longer server response times. Furthermore, my observation was that with every additional function activated in the config, the server response time increases.
> 
> 120.599999 UNEXPECTED LONG FRAME DETECTED: 66.47ms elapsed, 65.91ms sim time, 3 ticks, 7706..7708. 120.694851 UNEXPECTED LONG FRAME DETECTED: 94.85ms elapsed, 94.28ms sim time, 5 ticks, 7709..7713. 120.815040 UNEXPECTED LONG FRAME DETECTED: 120.19ms elapsed, 119.53ms sim time, 6 ticks, 7714..7719. Excessive frame time of 120.19ms clamped. Acting as if the frame only took 100.00ms 120.923818 UNEXPECTED LONG FRAME DETECTED: 108.78ms elapsed, 108.27ms sim time, 6 ticks, 7720..7725. Excessive frame time of 108.78ms clamped. Acting as if the frame only took 100.00ms 121.057598 UNEXPECTED LONG FRAME DETECTED: 133.78ms elapsed, 133.14ms sim time, 7 ticks, 7726..7732. Excessive frame time of 133.78ms clamped. Acting as if the frame only took 100.00ms 121.168850 UNEXPECTED LONG FRAME DETECTED: 111.25ms elapsed, 110.68ms sim time, 6 ticks, 7733..7738. Excessive frame time of 111.25ms clamped. Acting as if the frame only took 100.00ms 121.240432 UNEXPECTED LONG FRAME DETECTED: 71.58ms elapsed, 71.22ms sim time, 6 ticks, 7739..7744. 121.302142 UNEXPECTED LONG FRAME DETECTED: 61.71ms elapsed, 61.39ms sim time, 5 ticks, 7745..7749. 121.350852 UNEXPECTED LONG FRAME DETECTED: 48.71ms elapsed, 48.41ms sim time, 4 ticks, 7750..7753. 121.386033 UNEXPECTED LONG FRAME DETECTED: 35.18ms elapsed, 34.91ms sim time, 3 ticks, 7754..7756. 121.412232 UNEXPECTED LONG FRAME DETECTED: 26.20ms elapsed, 25.88ms sim time, 2 ticks, 7757..7758. 121.436107 UNEXPECTED LONG FRAME DETECTED: 23.88ms elapsed, 23.65ms sim time, 2 ticks, 7759..7760.
> 
> ![grafik](https://private-user-images.githubusercontent.com/55334802/321984568-40f2d15d-2b93-405a-954a-b57d488502c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDMzMTUsIm5iZiI6MTcxMjk0MzAxNSwicGF0aCI6Ii81NTMzNDgwMi8zMjE5ODQ1NjgtNDBmMmQxNWQtMmI5My00MDVhLTk1NGEtYjU3ZDQ4ODUwMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE3MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2UyZThkZTIwNTZkOGVhMmNmZjIwMDUwYzFhZjZiOTVjMDgzZDIwZTM4NGJlOGQ0NTNhNjYyZjI3MzBlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oBehYawRJHocNSUbJ4oUF1bcgpI3-No0ZzO8ASbEIAY) ![grafik](https://private-user-images.githubusercontent.com/55334802/321984820-f5057d41-2c41-4c5b-8e14-03c0d1440479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDMzMTUsIm5iZiI6MTcxMjk0MzAxNSwicGF0aCI6Ii81NTMzNDgwMi8zMjE5ODQ4MjAtZjUwNTdkNDEtMmM0MS00YzViLThlMTQtMDNjMGQxNDQwNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE3MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzM4NjEzMWRmZDVmYjk3NjkyOThkMjBiMDg5MWY0ZDZlN2RkZTBhMTg5MDQxMWU0ZTQ4MDZmMTgyMDExNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Yr4Naz94oi7kAHmM5DZWl129KhBU6dXbAkdpZpIcl0)

i dont think its from vote goldkingz 
try this disable plugin one by one and see who cause this 

test it alone nothing happen

**Comment by oqyh** [comment]
ill close it as no reply
