### ISSUE TITLE
Change VoteBanned_TimeInDays to minutes

### ISSUE THREAD

**Issue by automixes** [oqyh/cs2-Vote-GoldKingZ#5]
Hello!
If possible, make a parameter that indicates the duration of the ban in minutes

**Comment by oqyh** [comment]
> Hello! If possible, make a parameter that indicates the duration of the ban in minutes

will do

**Comment by oqyh** [comment]
> Hello! If possible, make a parameter that indicates the duration of the ban in minutes

Change VoteBanned_TimeInDays To VoteBanned_TimeInMins
Added VoteBanned_ChangeTimeInMinsToDays

https://github.com/oqyh/cs2-Vote-GoldKingZ/releases/tag/1.0.9

**Comment by oqyh** [comment]
ill close this issue 
if you have further issue reply  this message
