### ISSUE TITLE
Voteban doesn't ban

### ISSUE THREAD

**Issue by WeirdPhrog** [oqyh/cs2-Vote-GoldKingZ#7]
After the number of votes reaches the required number, the plugins write that the player is banned, but he continues to play on the server. No errors. Plugin ver 1.0.9

**Comment by WeirdPhrog** [comment]
https://github.com/oqyh/cs2-Vote-GoldKingZ/blob/0b1c5f79a9b457e9a552717e0cd8c0c880932376/Vote%20Banned/VoteBanned.cs#L1329
I'm sure it's better to use kickid {userid}. Players usually use unreadable nicknames.

**Comment by oqyh** [comment]
> https://github.com/oqyh/cs2-Vote-GoldKingZ/blob/0b1c5f79a9b457e9a552717e0cd8c0c880932376/Vote%20Banned/VoteBanned.cs#L1329
> 
> 
> I'm sure it's better to use kickid {userid}. Players usually use unreadable/bugged nicknames.

can you show me ur config

**Comment by WeirdPhrog** [comment]
[config.json](https://github.com/oqyh/cs2-Vote-GoldKingZ/files/15143274/config.json)

**Comment by oqyh** [comment]
> [config.json](https://github.com/oqyh/cs2-Vote-GoldKingZ/files/15143274/config.json)

can you give me player name was

**Comment by WeirdPhrog** [comment]
I don't remember :( 
I think you should just change the command "kick name" to "kickid userid", also because in cs2 there can be many players with the same nickname, lol

**Comment by WeirdPhrog** [comment]
> > I don't remember :( I think you should just change "kick name" to "kickid userid" in all sources, also because in cs2 there can be many players with the same nickname, lol
> 
> sorry for delay working on other project it target banned play never goes to other player same nickname using kickid userid will kick depend number id at status not good option because of bug that happen ids goes 255 random

Never head about this bug. Everyone uses kickid - https://github.com/daffyyyy/CS2-SimpleAdmin/blob/c25d3c4bda252663b1c961ee66c0f6d6edbb483d/Helper.cs#L130C3-L130C4

**Comment by oqyh** [comment]
> > > I don't remember :( I think you should just change "kick name" to "kickid userid" in all sources, also because in cs2 there can be many players with the same nickname, lol
> > 
> > 
> > sorry for delay working on other project it target banned play never goes to other player same nickname using kickid userid will kick depend number id at status not good option because of bug that happen ids goes 255 random
> 
> Never heard of this bug. Everyone uses kickid - https://github.com/daffyyyy/CS2-SimpleAdmin/blob/c25d3c4bda252663b1c961ee66c0f6d6edbb483d/Helper.cs#L130C3-L130C4

userid used id of players sometimes it bugs for some reason i use name targer controller -> playername 


here is what i ment

![2024_05_02_15_53_29_367_Discord_plugin_releases_CounterStrikeSharp](https://github.com/oqyh/cs2-Vote-GoldKingZ/assets/48490385/9889427f-dc23-4704-9cf6-db1f63c88dc8)

**Comment by WeirdPhrog** [comment]
I don't see any problem here. I never seen that bug on my servers. As I said, perform actions by player names is really bad idea.

**Comment by oqyh** [comment]
> I don't see any problem here. I never seen that bug on my servers. As I said, perform actions by player names is really bad idea.

as i said its not just name 
its target controller then playername
target controller cannot be mixed other players
if you want to change it its public source you can change it by yourself if you dont like it
